name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: cargo build --release

      # TODO uncomment when tests is ready
      #- name: Run tests
      #  run: cargo test --release

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check
