name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Determine next version bump from Conventional Commits
        id: bump
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s%n%b")
          if echo "$COMMITS" | grep -q "BREAKING CHANGE"; then
            echo "level=major" >> $GITHUB_OUTPUT
          elif echo "$COMMITS" | grep -q "^feat"; then
            echo "level=minor" >> $GITHUB_OUTPUT
          else
            echo "level=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version & tag
        run: |
          cargo release ${{ steps.bump.outputs.level }} --execute --no-publish --no-confirm

      - name: Build binary
        run: cargo build --release

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/zipwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
