name: Publish Release

# TODO uncomment when release flow is ready
#on:
#  push:
#    tags:
#      - 'v*.*.*'

permissions: { }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # TODO fetch version and create tag
      #- name: Create tag

      # TODO create release ??

      - name: Build binary
        run: cargo build --release

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/zipwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
