name: Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.changes.outputs.any_changed }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check if main has changed since last release
        id: changes
        run: |
          if git diff --quiet $(git describe --tags --abbrev=0)..HEAD; then
            echo "No changes since last release."
            echo "any_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "any_changed=true" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check_changes
    if: needs.check_changes.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Bump version and create tag
        run: |
          cargo release ${{ github.event.inputs.version_bump }} --execute --no-confirm
        env:
          CARGO_RELEASE_TAG_PREFIX: "v"

      - name: Build binary
        run: cargo build --release

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/zipwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
