name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/zipwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
